name: Publish AAR Release

on:
  push:
    tags:
      - 'v-*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build AAR
        run: ./gradlew :botsi:assembleRelease

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: botsi/build/outputs/aar/*.aar
          body: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
